### ISSUE TITLE
Builds fails on musl: mismatch types on fs_type_unsupported

### ISSUE THREAD

**Issue by ErikSchlyter** [always-further/nono#1315]
### What happened?

I try `cargo build --release` on my Alpine Linux system (musl libc).

It seems to be introduced in #1207 

### What did you expect to happen?

Build should be successful.

### Steps to reproduce

`cargo build --release`

### Relevant output or logs

```shell
error[E0308]: mismatched types
   --> crates/nono/src/sandbox/linux.rs:438:32
    |
438 |         if fs_type_unsupported(stat.f_type) {
    |            ------------------- ^^^^^^^^^^^ expected `i64`, found `u64`
    |            |
    |            arguments to this function are incorrect
    |
note: function defined here
   --> crates/nono/src/sandbox/linux.rs:405:4
    |
405 | fn fs_type_unsupported(f_type: libc::c_long) -> bool {
    |    ^^^^^^^^^^^^^^^^^^^ --------------------
help: you can convert a `u64` to an `i64` and panic if the converted value doesn't fit
    |
438 |         if fs_type_unsupported(stat.f_type.try_into().unwrap()) {
    |                                           ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
```

### nono version

v0.66.0

### Operating system

Linux

### OS version / distro

Alpine Linux v3.22

### Kernel version (Linux only)

6.12.69-0-lts

### Profile (if relevant)

```json

```

**Comment by SequeI** [comment]
Apologies! Linked PR now adds musl to our cross compile CI tests so we should be able to catch these issues out before releases now. Also fixed all compilation issues between musl/glibc cleanly via `#[cfg(target_env = "musl")]` etc
